apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2024-01-26T21:32:02Z"
    generateName: webapp-78d6769cf8-
    labels:
      app: webapp
      pod-template-hash: 78d6769cf8
    name: webapp-78d6769cf8-d7c96
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: webapp-78d6769cf8
      uid: 021b28e3-dcd5-47f9-951a-ac4bfcddc4e7
    resourceVersion: "539789"
    uid: 2c92761e-a989-4324-803b-2a2b8da97ec6
  spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-bgpxc
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: docker-desktop
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-bgpxc
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-01-26T21:32:02Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-01-26T21:32:09Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-01-26T21:32:09Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-01-26T21:32:02Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://592629fc7848508ec04cce73e950a5eaf55886ad95617610a93b79993175b59c
      image: nginx:latest
      imageID: docker-pullable://nginx@sha256:4c0fdaa8b6341bfdeca5f18f7837462c80cff90527ee35ef185571e1c327beac
      lastState: {}
      name: nginx
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-01-26T21:32:09Z"
    hostIP: 192.168.65.3
    phase: Running
    podIP: 10.1.0.149
    podIPs:
    - ip: 10.1.0.149
    qosClass: BestEffort
    startTime: "2024-01-26T21:32:02Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2024-01-26T21:32:02Z"
    generateName: webapp-78d6769cf8-
    labels:
      app: webapp
      pod-template-hash: 78d6769cf8
    name: webapp-78d6769cf8-l4mt2
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: webapp-78d6769cf8
      uid: 021b28e3-dcd5-47f9-951a-ac4bfcddc4e7
    resourceVersion: "539805"
    uid: 4605e3f5-e57b-47c4-a609-efbfa61dd645
  spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-xpqhw
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: docker-desktop
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-xpqhw
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-01-26T21:32:02Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-01-26T21:32:12Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-01-26T21:32:12Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-01-26T21:32:02Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://5369ebc5610e192ba15f18db62d03f515dd55f8ea199a93ae38759db3ce6ebde
      image: nginx:latest
      imageID: docker-pullable://nginx@sha256:4c0fdaa8b6341bfdeca5f18f7837462c80cff90527ee35ef185571e1c327beac
      lastState: {}
      name: nginx
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-01-26T21:32:12Z"
    hostIP: 192.168.65.3
    phase: Running
    podIP: 10.1.0.151
    podIPs:
    - ip: 10.1.0.151
    qosClass: BestEffort
    startTime: "2024-01-26T21:32:02Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2024-01-26T21:32:02Z"
    generateName: webapp-78d6769cf8-
    labels:
      app: webapp
      pod-template-hash: 78d6769cf8
    name: webapp-78d6769cf8-pt7m2
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: webapp-78d6769cf8
      uid: 021b28e3-dcd5-47f9-951a-ac4bfcddc4e7
    resourceVersion: "539775"
    uid: 99c4ce79-7f9e-425b-b1f3-16b71fe15c6c
  spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-7zt76
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: docker-desktop
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-7zt76
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-01-26T21:32:02Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-01-26T21:32:06Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-01-26T21:32:06Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-01-26T21:32:02Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://02c152a738161e52cb031eec5d6776e46ec0a9d3a13e03de4efe35eff9b7ae32
      image: nginx:latest
      imageID: docker-pullable://nginx@sha256:4c0fdaa8b6341bfdeca5f18f7837462c80cff90527ee35ef185571e1c327beac
      lastState: {}
      name: nginx
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-01-26T21:32:06Z"
    hostIP: 192.168.65.3
    phase: Running
    podIP: 10.1.0.147
    podIPs:
    - ip: 10.1.0.147
    qosClass: BestEffort
    startTime: "2024-01-26T21:32:02Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2024-01-26T21:32:02Z"
    generateName: webapp-78d6769cf8-
    labels:
      app: webapp
      pod-template-hash: 78d6769cf8
    name: webapp-78d6769cf8-w7sjv
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: webapp-78d6769cf8
      uid: 021b28e3-dcd5-47f9-951a-ac4bfcddc4e7
    resourceVersion: "539781"
    uid: 452cdee8-9d30-4c85-a56c-a5a9634dc316
  spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-dpr79
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: docker-desktop
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-dpr79
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-01-26T21:32:02Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-01-26T21:32:07Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-01-26T21:32:07Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-01-26T21:32:02Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://905a987389bc08e5fcfb6da9239d1729303700f8c25419e4c50248c66e572b97
      image: nginx:latest
      imageID: docker-pullable://nginx@sha256:4c0fdaa8b6341bfdeca5f18f7837462c80cff90527ee35ef185571e1c327beac
      lastState: {}
      name: nginx
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-01-26T21:32:07Z"
    hostIP: 192.168.65.3
    phase: Running
    podIP: 10.1.0.150
    podIPs:
    - ip: 10.1.0.150
    qosClass: BestEffort
    startTime: "2024-01-26T21:32:02Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2024-01-26T21:32:02Z"
    generateName: webapp-78d6769cf8-
    labels:
      app: webapp
      pod-template-hash: 78d6769cf8
    name: webapp-78d6769cf8-x9clv
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: webapp-78d6769cf8
      uid: 021b28e3-dcd5-47f9-951a-ac4bfcddc4e7
    resourceVersion: "539797"
    uid: 6ed184fa-29eb-46b6-80fb-6ffb76671474
  spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-sstsl
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: docker-desktop
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-sstsl
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-01-26T21:32:02Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-01-26T21:32:11Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-01-26T21:32:11Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-01-26T21:32:02Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://470510506a1b851c80a52f036098b44262294bdf98b878e6393b1f0c2a33a393
      image: nginx:latest
      imageID: docker-pullable://nginx@sha256:4c0fdaa8b6341bfdeca5f18f7837462c80cff90527ee35ef185571e1c327beac
      lastState: {}
      name: nginx
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-01-26T21:32:11Z"
    hostIP: 192.168.65.3
    phase: Running
    podIP: 10.1.0.148
    podIPs:
    - ip: 10.1.0.148
    qosClass: BestEffort
    startTime: "2024-01-26T21:32:02Z"
kind: List
metadata:
  resourceVersion: ""
