apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2024-01-27T16:07:33Z"
    generateName: webapp-78d6769cf8-
    labels:
      app: webapp
      pod-template-hash: 78d6769cf8
    name: webapp-78d6769cf8-69rvf
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: webapp-78d6769cf8
      uid: 265e869e-1dc0-4c97-bb83-69be35f6f591
    resourceVersion: "5793"
    uid: 4e0ca344-6aa0-4d58-9565-1cf40454f46c
  spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-vztlj
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: docker-desktop
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-vztlj
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-01-27T16:07:33Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-01-27T16:07:43Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-01-27T16:07:43Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-01-27T16:07:33Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://25f57e8b4568ee9f23f7cc72cae57ff61da5c0ed6b5d77375f71af5bcea59825
      image: nginx:latest
      imageID: docker-pullable://nginx@sha256:4c0fdaa8b6341bfdeca5f18f7837462c80cff90527ee35ef185571e1c327beac
      lastState: {}
      name: nginx
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-01-27T16:07:42Z"
    hostIP: 192.168.65.3
    phase: Running
    podIP: 10.1.0.232
    podIPs:
    - ip: 10.1.0.232
    qosClass: BestEffort
    startTime: "2024-01-27T16:07:33Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2024-01-27T16:07:33Z"
    generateName: webapp-78d6769cf8-
    labels:
      app: webapp
      pod-template-hash: 78d6769cf8
    name: webapp-78d6769cf8-f7xvb
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: webapp-78d6769cf8
      uid: 265e869e-1dc0-4c97-bb83-69be35f6f591
    resourceVersion: "5768"
    uid: 53157530-afcf-46af-a6a0-af2cdc5eef0b
  spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-2bfrr
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: docker-desktop
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-2bfrr
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-01-27T16:07:33Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-01-27T16:07:38Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-01-27T16:07:38Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-01-27T16:07:33Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://06093a615aa3b0e9da62d9e79b55e758f6d0b3ed897fb22b75ab539a2bf4c1d5
      image: nginx:latest
      imageID: docker-pullable://nginx@sha256:4c0fdaa8b6341bfdeca5f18f7837462c80cff90527ee35ef185571e1c327beac
      lastState: {}
      name: nginx
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-01-27T16:07:37Z"
    hostIP: 192.168.65.3
    phase: Running
    podIP: 10.1.0.229
    podIPs:
    - ip: 10.1.0.229
    qosClass: BestEffort
    startTime: "2024-01-27T16:07:33Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2024-01-27T16:07:33Z"
    generateName: webapp-78d6769cf8-
    labels:
      app: webapp
      pod-template-hash: 78d6769cf8
    name: webapp-78d6769cf8-jmhq9
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: webapp-78d6769cf8
      uid: 265e869e-1dc0-4c97-bb83-69be35f6f591
    resourceVersion: "5760"
    uid: ca211cd4-66e4-417d-9d6e-cb9fbcd7c46a
  spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-9jk8c
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: docker-desktop
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-9jk8c
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-01-27T16:07:33Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-01-27T16:07:36Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-01-27T16:07:36Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-01-27T16:07:33Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://07e51e73382ce204ef4816f03413459549ecf1346fabbc6891af68ccc9199c6e
      image: nginx:latest
      imageID: docker-pullable://nginx@sha256:4c0fdaa8b6341bfdeca5f18f7837462c80cff90527ee35ef185571e1c327beac
      lastState: {}
      name: nginx
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-01-27T16:07:35Z"
    hostIP: 192.168.65.3
    phase: Running
    podIP: 10.1.0.228
    podIPs:
    - ip: 10.1.0.228
    qosClass: BestEffort
    startTime: "2024-01-27T16:07:33Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2024-01-27T16:07:33Z"
    generateName: webapp-78d6769cf8-
    labels:
      app: webapp
      pod-template-hash: 78d6769cf8
    name: webapp-78d6769cf8-kjslv
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: webapp-78d6769cf8
      uid: 265e869e-1dc0-4c97-bb83-69be35f6f591
    resourceVersion: "5777"
    uid: 501b70ba-9a41-47d6-99ce-dc9d1ff733f7
  spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-78b28
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: docker-desktop
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-78b28
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-01-27T16:07:33Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-01-27T16:07:40Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-01-27T16:07:40Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-01-27T16:07:33Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://c7bf6a04885ebc6a815936a01f8570fd372251b8c411e0f590e36c09fc29e34e
      image: nginx:latest
      imageID: docker-pullable://nginx@sha256:4c0fdaa8b6341bfdeca5f18f7837462c80cff90527ee35ef185571e1c327beac
      lastState: {}
      name: nginx
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-01-27T16:07:39Z"
    hostIP: 192.168.65.3
    phase: Running
    podIP: 10.1.0.230
    podIPs:
    - ip: 10.1.0.230
    qosClass: BestEffort
    startTime: "2024-01-27T16:07:33Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2024-01-27T16:07:33Z"
    generateName: webapp-78d6769cf8-
    labels:
      app: webapp
      pod-template-hash: 78d6769cf8
    name: webapp-78d6769cf8-vr7t2
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: webapp-78d6769cf8
      uid: 265e869e-1dc0-4c97-bb83-69be35f6f591
    resourceVersion: "5784"
    uid: 6eb6913a-2631-4a38-92f4-e585dd705f0a
  spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-ncgrg
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: docker-desktop
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-ncgrg
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-01-27T16:07:33Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-01-27T16:07:41Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-01-27T16:07:41Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-01-27T16:07:33Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://6ae8ff044cc3314427714c45ec79186001eb8f17fae125dd69598ea7118195f8
      image: nginx:latest
      imageID: docker-pullable://nginx@sha256:4c0fdaa8b6341bfdeca5f18f7837462c80cff90527ee35ef185571e1c327beac
      lastState: {}
      name: nginx
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-01-27T16:07:40Z"
    hostIP: 192.168.65.3
    phase: Running
    podIP: 10.1.0.231
    podIPs:
    - ip: 10.1.0.231
    qosClass: BestEffort
    startTime: "2024-01-27T16:07:33Z"
kind: List
metadata:
  resourceVersion: ""
