apiVersion: v1
items:
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "5"
      deployment.kubernetes.io/max-replicas: "7"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2024-01-26T21:32:02Z"
    generation: 1
    labels:
      app: webapp
      pod-template-hash: 78d6769cf8
    name: webapp-78d6769cf8
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: webapp
      uid: f6bf69fb-d157-4c19-8cfb-42383c85b9f8
    resourceVersion: "539806"
    uid: 021b28e3-dcd5-47f9-951a-ac4bfcddc4e7
  spec:
    replicas: 5
    selector:
      matchLabels:
        app: webapp
        pod-template-hash: 78d6769cf8
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: webapp
          pod-template-hash: 78d6769cf8
      spec:
        containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 5
    fullyLabeledReplicas: 5
    observedGeneration: 1
    readyReplicas: 5
    replicas: 5
kind: List
metadata:
  resourceVersion: ""
