apiVersion: v1
items:
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "5"
      deployment.kubernetes.io/max-replicas: "7"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2024-01-27T16:07:33Z"
    generation: 1
    labels:
      app: webapp
      pod-template-hash: 78d6769cf8
    name: webapp-78d6769cf8
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: webapp
      uid: b4631926-3c88-405f-a35b-4ba393060ceb
    resourceVersion: "5794"
    uid: 265e869e-1dc0-4c97-bb83-69be35f6f591
  spec:
    replicas: 5
    selector:
      matchLabels:
        app: webapp
        pod-template-hash: 78d6769cf8
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: webapp
          pod-template-hash: 78d6769cf8
      spec:
        containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 5
    fullyLabeledReplicas: 5
    observedGeneration: 1
    readyReplicas: 5
    replicas: 5
kind: List
metadata:
  resourceVersion: ""
