apiVersion: v1
items:
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "5"
      deployment.kubernetes.io/max-replicas: "7"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2024-01-19T17:20:16Z"
    generation: 1
    labels:
      app: hr-web-app
      pod-template-hash: 57cd7b5799
    name: hr-web-app-57cd7b5799
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: hr-web-app
      uid: 131d83b0-cadc-4b76-b6ad-6a57019d9b79
    resourceVersion: "363455"
    uid: 706a293a-a142-418a-810e-b4ac4e246480
  spec:
    replicas: 5
    selector:
      matchLabels:
        app: hr-web-app
        pod-template-hash: 57cd7b5799
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: hr-web-app
          pod-template-hash: 57cd7b5799
      spec:
        containers:
        - image: kodekloud/webapp-color
          imagePullPolicy: Always
          name: webapp-color
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 5
    fullyLabeledReplicas: 5
    observedGeneration: 1
    readyReplicas: 5
    replicas: 5
kind: List
metadata:
  resourceVersion: ""
