apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-gidon
spec:
  containers:
  - name: redis-container
    image: redis:alpine
    volumeMounts:
    - name: redis-storage-volume
      mountPath: /data/redis
  volumes:
  - name: redis-storage-volume
    emptyDir: {}
