apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis-storage-gidon
  name: redis-storage-gidon
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: redis:alpine
    name: redis-storage-gidon
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
