apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: use-pvspec-gidon
spec:
  containers:
    - name: use-pv
      image: nginx
      volumeMounts:
        - name: hostbase
          mountPath: /hostbase
  volumes:
    - name: hostbase
      persistentVolumeClaim:
        claimName: pv-1
