apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        deployment.kubernetes.io/revision: "1"
        image_version: "1.16"
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        deployment.kubernetes.io/revision: "2"
        image_version: "1.17"
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
