apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  labels:
    app: messaging
spec:
  selector:
    app: messaging
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
