apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: use-pv
  name: use-pvspec-yourname
spec:
  containers:
  - image: nginx
    name: use-pv
    resources: {}
    volumeMounts:
    - name: pv-1
      mountPath: /data/hostbase
  volumes:
  - name: pv-1
    persistentVolumeClaim:
      claimName: pv-claim-1  # Replace with the actual PersistentVolumeClaim name
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
